### ISSUE TITLE
希望能先把找回密码不会去数据库检查邮箱是否存在的问题解决一下

### ISSUE THREAD

**Issue by AnniBear** [DrDeanWinchester/V2BoardPro#1]
希望能先把找回密码不会去数据库检查邮箱是否存在的问题解决一下，现在找回密码可以输入任意邮箱且不会去数据库验证该邮箱是否存在。

**Comment by DrDeanWinchester** [comment]
您说的应该是发送邮箱验证码接口，请在app/Http/Controllers/Passport/CommController.php文件第37行，添加如下代码：
        $user = User::where('email', $email)->first();
        if (!$user) {
            abort(500, __('This email is not registered in the system'));
        }
即可解决您说的问题，此问题将会在正式版中修复，请先手动进行修正。

**Comment by DrDeanWinchester** [comment]
由于现在无前端代码，最好的方式是前端代码传入一个类型代表用户是新注册还是找回密码，这样后端才可以做判断，故此先还原代码，等前端开源完毕后在进行全方面整改。
