### ISSUE TITLE
昨日节点流量排行 无法正常出数据

### ISSUE THREAD

**Issue by datang2020** [DrDeanWinchester/V2BoardPro#7]
突然出现的问题   服务器重启 环境重装 

supervisor服务   redis 都进行重装了 

还是不行     有解决办法吗  

这个问题会导致流量纪录也不显示

**Comment by cyril-cheng** [comment]
看看是不是api被墙了
我就是这个原因，给节点换个api域名就好了

**Comment by datang2020** [comment]
这个api是那个授权域名吗   机器都是国外的  就算墙了 跟国外也没关系吧

还有那个 充值 佣金 笔数那个图也不行  也没有了

**Comment by datang2020** [comment]
今天面板 直接 做系统 重新装了一遍 也还是不行

**Comment by datang2020** [comment]
刚才又看了下  恢复了 重装就好了   应该是队列出问题了
